---
title: "Map View"
output: html_document
---

```{css, echo = FALSE}
html *
  {
    color: #808080
    font-family: Arial !important;
  }

.leaflet {
  height: calc(100vh - 175px) !important;
  width: 100% !important;}

.leaflet .legend {
  font-size: 10px;
  line-height: 20px;
  opacity: 0.90;
}

.leaflet .leaflet-control-layers-expanded {
  opacity: 0.90;
  font-size: 10px;
  line-height: 20px;
}

.leaflet .leaflet-popup-content {
  opacity: 0.90;
  font-size: 10px;
  line-height: 20px;
  width:auto !important;
}

.leaflet .leaflet-control {
  opacity: 0.90;
}

th {
  padding: 5px;
  text-align: left;
}

td {
  padding: 10px;
  text-align: left;
}

a:hover {
  color: #FF0000;
  font-size: 110%;
}

tr:hover {background-color: #f5f5f5;}

.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(leaflet)
library(leaflet.extras)
library(tidyr)
library(sf)
# Get data ---------------------------------------------------------------------
## Fort Ord Boundaries
fo <- st_read("https://maps.fodis.net/server/rest/services/OpenData/AdministrativeBoundaries/FeatureServer/4/query?where=1%3D1&outFields=*&outSR=4326&f=json")
## Import our hand filled data
options(gargle_oauth_email = readLines(".credential/gmail"))
wants <- read_sheet("https://docs.google.com/spreadsheets/d/106uYNJ-YfZVJtI1ztw2PqKvF8YUzGsyPiHnWec4rV7w/edit#gid=1167995236")
## Get simple features, filter them, and nest them
api_url <- "https://maps.fodis.net/server/rest/services/OpenData/AdministrativeBoundaries/FeatureServer/1/query?where=1%3D1&outFields=*&outSR=4326&f=json"
fora <- st_read(api_url) %>% 
  filter(parcel_id %in% wants[["COE"]]) %>%
  merge(., wants, by.x = "parcel_id", by.y = "COE") %>%
  select(COE = parcel_id, APN = Match.APN, Owner = Match.Owner, Deed = Match.Deed, Note) %>%
  group_by(COE) %>%
  group_nest() %>%
  ungroup()
# Declare helper functions -----------------------------------------------------
unnested_row <- function(.df, .id, .var) {
  stopifnot(".df should be a data.frame"      = is.data.frame(.df),
            ".id should be a character"       = is.character(.id),
            ".var should be a character"      = is.character(.var),
            ".id not variable in data.frame"  = .id %in% names(.df))
  sapply(.df[[.id]], function(x) {
    paste0("<tr><th><b>", .var, ": </b></th><td>",
           paste0(.df[.df[[.id]]==x, "data"][[1]][[1]][[.var]], collapse = "</td><td>"),
           "</td></tr>")
    })
}
detect_string <- function(.df, .id, .var, .string) {
  stopifnot(".df should be a data.frame"      = is.data.frame(.df),
            ".id should be a character"       = is.character(.id),
            ".var should be a character"      = is.character(.var),
            ".string should be a character"   = is.character(.string),
            ".id not variable in data.frame"  = .id %in% names(.df))
  sapply(.df[[.id]], function(x) {
    temp <- .df[.df[[.id]] == x, "data"][[1]][[1]][[.var]]
    .string %in% temp
  })
}
get_geometry <- function(.df, .id) {
  stopifnot(".df should be a data.frame"    = is.data.frame(.df),
            ".id should be a character"     = is.character(.id),
            ".id not variable in character" = .id %in% names(.df))
  lapply(.df[[.id]], function(x) {
    temp <- .df[.df[[.id]] == x, "data"][[1]][[1]][['geometry']]
    temp[[1]]
    })
}
# Create html table rows by value ----------------------------------------------
fora[["Owner_Row"]] <- unnested_row(fora, "COE", "Owner")
fora[["APN_Row"]]   <- unnested_row(fora, "COE", "APN")
fora[["Deed_Row"]]  <- unnested_row(fora, "COE", "Deed")
# Pull out geometry from nested list and make it a geometry --------------------
fora[["geometry"]] <- get_geometry(fora, "COE")
fora <- st_as_sf(fora)
# Color ------------------------------------------------------------------------
fora[["color"]] <- if_else(
  detect_string(fora, "COE", "Owner", "FORT ORD REUSE AUTHORITY"),
  true = "red", false = "blue")
fora[["color"]] <- if_else(
  detect_string(fora, "COE", "Owner", "") & !detect_string(fora, "COE", "Owner", "FORT ORD REUSE AUTHORITY"),
  true = "yellow", false = fora[["color"]])
fora[["color"]] <- if_else(
  detect_string(fora, "COE", "Note", "Road"),
  true = "white", false = fora[["color"]])
names(fora$color) <- NULL # removed names from the name vector for leaflet
```

```{r, echo = FALSE, fig.align='center'}
# Map --------------------------------------------------------------------------
leaflet() %>%
  addProviderTiles(provider = providers[['Esri.WorldGrayCanvas']],
                   group    = "Imagery") %>%
  setView(lng = -121.775, lat = 36.63,
            zoom = 12.3) %>%
  addPolygons(data = fo, fill = FALSE, weight = 2, color = "grey",
              opacity = 1, dashArray = 4, 
              label = "Former Fort Ord Boundary") %>%
  addPolygons(data = fora, color = "black", fill = TRUE,
              label = ~COE, group = "searchable",
              fillColor = ~color, opacity = 1, weight = 1, fillOpacity = 0.5,
              popup = case_when(
                # Roads
                detect_string(fora, "COE", "Note", "Road") ~ paste0(
                  "<table>",
                  "<tr><th>COE: </th><td>", fora[["COE"]], "</td></tr>",
                  "</table><p><b>NOTE: </b>No APN on record for this parcel.</p>"),
                # Red
                detect_string(fora, "COE", "Owner", "FORT ORD REUSE AUTHORITY") ~ paste0(
                  "<p><b>COE: </b>",fora[["COE"]], "</p>",
                  "<table>",
                  fora[["APN_Row"]], fora[["Owner_Row"]], fora[["Deed_Row"]],
                  "</table>"),
                # BLUE
                !detect_string(fora, "COE", "Owner", "FORT ORD REUSE AUTHORITY") & !detect_string(fora, "COE", "Note", "Road") & !detect_string(fora, "COE", "Owner", "")   ~ paste0(
                  "<p><b>COE: </b>",fora[["COE"]], "</p>",
                  "<table>",
                  fora[["APN_Row"]], fora[["Owner_Row"]], fora[["Deed_Row"]],
                  "</table>"),
                # Yellow
                !detect_string(fora, "COE", "Note", "Road") & detect_string(fora, "COE", "Owner", "") ~paste0(
                  "<table>",
                  "<tr><th>COE: </th><td>", fora[["COE"]], "</td></tr>",
                  fora[["APN_Row"]],
                  "</table><p><b>NOTE: </b>There is either no parcel found at this location, or the parcel polygon at this location is temporarily suspended pending modifications in progress by the County Assessor and Parcelquest staff. </p>"))) %>%
  addLegend(color = c("white", "red", "yellow", "blue"),
            labels = c("No APN", "FORA Owned", "Records pending", "Transfer complete"),
            opacity = 1, position = "bottomright",
            title = "Parcel Status") %>%
  addSearchFeatures(targetGroups = "searchable", 
                    options      = searchFeaturesOptions(zoom                 = 15,
                                                         openPopup            = TRUE,
                                                         moveToLocation       = TRUE,
                                                         position             = "topright",
                                                         hideMarkerOnCollapse = TRUE,
                                                         textPlaceholder      = "Search COE...",
                                                         autoCollapse         = TRUE))
```

